export const GAME_CONFIG = {
  wormsPerBaby: 4,
  carryCapacity: 4,
  clutchSizeRange: {
    min: 3,
    max: 6,
  },
  hatchDelay: {
    quickMin: 5,
    quickMax: 10,
    middleMin: 18,
    middleMax: 50,
    slowMin: 95,
    slowMax: 150,
    slowChance: 0.15,
  },
  feedCooldown: 0.3,
  roundDelay: 2.25,
  playerSpeed: 5.6,
  flockFollowSpeed: 4,
  flockPatrolSpeed: 1.35,
  patrolReach: 0.24,
  patrolHungryDelay: {
    min: 40,
    max: 90,
  },
  collectRadius: 1.15,
  feedRadius: 1.45,
  wormSpeed: 0.85,
  wormRespawnDelay: 2.8,
  wormReach: 0.2,
  wormCountTotal: 12,
  playerSpawn: [-8.8, 0.3, 1.2] as const,
  cameraZoom: {
    default: 38,
    min: 26,
    max: 56,
    step: 2,
  },
  mapBounds: {
    minX: -15.5,
    maxX: 15.5,
    minZ: -10.5,
    maxZ: 10.8,
  },
} as const
